added hw7_2
prfms/HW1semester pull request #6
Opened 2024-04-03 00:22 UTC by prfms

2024-04-03 18:12 UTC, yurii-litvinov requested changes

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTree.h
> +Error fillTree(Tree **root, FILE *fileName);
Так FILE или fileName? Тип параметра противоречит имени.
Лучше имя файла принимать, чтобы вызывающему не приходилось открывать файл и потом закрывать ещё.

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTree.c
> +                    return MemoryAllocationError;
Уже успели аллоцировать память под root, но никуда её не привесили, так что она потеряется. Надо почистить

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTree.c
> +            if (rightValue == 0){
Пробела не хватает, и скобка не на месте

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTree.c
> +    int rightValue = evaluateTree(tree->rightChild, error);
А что-то тут error не проверяется, может, дальше считать уже и не надо

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTree.c
> +}
Надо ещё root NULL присвоить, чтобы не было висячего указателя

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTree.h
> +#include <stdio.h>
```suggestion
#define HOMEWORKS_OPERATIONTREE_H

#include <stdio.h>
```

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTreeTest.c
> +bool test2()
Имена тестов ужасны

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTreeTest.h
> +#include "OperationTree.h"
```suggestion
#define HOMEWORKS1SEMESTER_OPERATIONTREETEST_H

#include "OperationTree.h"
```

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/OperationTreeTest.h
> +bool tests();
Надо комментарии

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/main.c
> +        return 0;
Не, не 0 :)

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/main.c
> +        return 0;
Если файл пуст, то feof будет false до первой попытки чтения, так что такое себе. Плюс если файл пуст, его никто не закроет

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/main.c
> +        return 0;
Не 0, и файл ещё надо закрыть

2024-04-03 18:12 UTC, yurii-litvinov commented on HW7/main.c
> +    if (error != Ok){
```suggestion
    if (error != Ok)
    {
```

2024-04-05 02:35 UTC, prfms commented on HW7/OperationTree.h
> +Error fillTree(Tree **root, FILE *fileName);
Тогда придется открывать файл в fillTree, но функция рекурсивна, поэтому файл будет открываться каждый раз заново. Может оставить все-таки FILE *?

2024-11-11 22:00 UTC, merged